name: Build and Test PR Changes

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.14.2]
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Packages
        run: |
          npm install lerna -g
          npx lerna bootstrap

      - name: Check Lint
        run: |
          npm run lint:fix
      
      - name: Build Packages
        run: |
          npm run build
