name: Publish packages to NPM

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.14.2]
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Packages
        run: |
          npm install lerna -g
      
      - name: Check Lint
        run: |
          npx lerna bootstrap
          yarn run lint --fix
      
      - name: Build Packages
        run: |
          yarn run build
      
      - name: Publish Packages
        run: |
          npx lerna publish from-package
